import React, { createContext, useContext, useState, useEffect, ReactNode } from "react";
import { AlertEvent } from "@/components/AlertsPanel";

// Define the heatmap point interface based on the UI component
interface HeatPoint {
    x: number;
    y: number;
    intensity: number;
}

export interface LogEntry {
    id: string;
    timestamp: string;
    camera: string;
    event: string;
    details: string;
    severity: "HIGH" | "MEDIUM" | "LOW";
}

export interface ArchiveFile {
    id: string;
    name: string;
    size: string;
    duration: string;
    uploadDate: string;
    status: "Queued" | "Processing" | "Completed" | "Failed";
    progress: number;
    findings: number;
    source: string;
    fileObj?: File;
    videoUrl?: string;
    findingsArray?: any[];
}

interface MonitoringContextType {
    alerts: AlertEvent[];
    logs: LogEntry[];
    heatPoints: HeatPoint[];
    totalDetections: number;
    detectionStats: Record<string, number>;
    activeCameras: number;
    fps: number;
    archiveFiles: ArchiveFile[];
    handleDetection: (label: string, confidence: number) => void;
    addArchiveFiles: (newFiles: ArchiveFile[]) => void;
    processArchiveFile: (id: string) => Promise<void>;
}

const MonitoringContext = createContext<MonitoringContextType | undefined>(undefined);

export const MonitoringProvider = ({ children }: { children: ReactNode }) => {
    const [alerts, setAlerts] = useState<AlertEvent[]>([]);
    const [logs, setLogs] = useState<LogEntry[]>([]);
    const [heatPoints, setHeatPoints] = useState<HeatPoint[]>([]);
    const [totalDetections, setTotalDetections] = useState(0);
    const [detectionStats, setDetectionStats] = useState<Record<string, number>>({});
    const [activeCameras, setActiveCameras] = useState(1);
    const [fps, setFps] = useState(0);
    const [archiveFiles, setArchiveFiles] = useState<ArchiveFile[]>([]);

    // For the moment, we will keep heatPoints empty here as it's generated by the Python engine
    // Alternatively, the python engine provides `/heatmap/{cam_id}` which returns a JPEG.

    // Dummy internal handler, the real detections happen on the Python backend via OpenCV
    const handleDetection = (label: string, confidence: number) => {
        // Left empty as detection is handled by backend YOLO
    };

    const addArchiveFiles = (newFiles: ArchiveFile[]) => {
        setArchiveFiles(prev => [...newFiles, ...prev]);
    };

    const processArchiveFile = async (id: string) => {
        const fileToProcess = archiveFiles.find(f => f.id === id);
        if (!fileToProcess || !fileToProcess.fileObj) return;

        setArchiveFiles(prev => prev.map(f => f.id === id ? { ...f, status: "Processing" as const, progress: 5 } : f));

        const formData = new FormData();
        formData.append("file", fileToProcess.fileObj);

        try {
            const response = await fetch("/archive/analyze", {
                method: "POST",
                body: formData,
            });

            if (!response.ok) throw new Error("Upload failed");
            const data = await response.json();
            const jobId = data.job_id;

            let currentProgress = 10;

            const pollInterval = setInterval(async () => {
                try {
                    const statusRes = await fetch(`/archive/status/${jobId}`);
                    if (statusRes.ok) {
                        const statusData = await statusRes.json();

                        if (statusData.status === "Completed") {
                            clearInterval(pollInterval);
                            setArchiveFiles(prev => prev.map(f => {
                                if (f.id !== id) return f;
                                return {
                                    ...f,
                                    status: "Completed" as const,
                                    progress: 100,
                                    findings: statusData.findings?.length || 0,
                                    videoUrl: statusData.video_url,
                                    findingsArray: statusData.findings
                                };
                            }));
                        } else if (statusData.status === "Failed") {
                            clearInterval(pollInterval);
                            setArchiveFiles(prev => prev.map(f => f.id === id ? { ...f, status: "Failed" as const } : f));
                        } else {
                            currentProgress = Math.min(currentProgress + 8, 95);
                            setArchiveFiles(prev => prev.map(f => f.id === id ? { ...f, progress: currentProgress } : f));
                        }
                    }
                } catch (pollErr) {
                    console.error("Poll error", pollErr);
                }
            }, 2000);

        } catch (error) {
            console.error("Upload error", error);
            setArchiveFiles(prev => prev.map(f => f.id === id ? { ...f, status: "Failed" as const } : f));
        }
    };

    useEffect(() => {
        // Poll the backend API for real alerts and event totals
        const fetchRealDetections = async () => {
            try {
                // Fetch Live Alerts
                const alertsResponse = await fetch("/alerts");
                if (alertsResponse.ok) {
                    const data = await alertsResponse.json();
                    // Map backend event structure to UI AlertEvent structure
                    const formattedAlerts: AlertEvent[] = data.alerts.map((a: any) => ({
                        id: String(a.id),
                        type: a.object.toUpperCase() + " DETECTED",
                        severity: a.level === "High" ? "HIGH" : a.level === "Medium" ? "MEDIUM" : "LOW",
                        timestamp: new Date(a.timestamp).toLocaleTimeString(),
                        camera: a.camera_id || "cam1" // Use dynamic ID if available, fallback to cam1
                    }));
                    setAlerts(formattedAlerts);
                }

                // Fetch Total Detections Count (from /events/count)
                const countResponse = await fetch("/events/count");
                if (countResponse.ok) {
                    const countData = await countResponse.json();
                    setTotalDetections(countData.count);
                }

                // Fetch Recent Events for Logs
                const eventsResponse = await fetch("/events?limit=100");
                if (eventsResponse.ok) {
                    const eventsData = await eventsResponse.json();

                    const formattedLogs: LogEntry[] = eventsData.events.map((e: any) => ({
                        id: String(e.id),
                        timestamp: new Date(e.timestamp).toLocaleString(),
                        camera: e.camera_source || "cam1",
                        event: `Detected ${e.object_class}`,
                        details: `Confidence: ${(e.confidence * 100).toFixed(1)}%`,
                        severity: "MEDIUM"
                    }));
                    setLogs(formattedLogs);
                }

                // Fetch Camera Status
                const camerasResponse = await fetch("/cameras");
                if (camerasResponse.ok) {
                    const camerasData = await camerasResponse.json();
                    setActiveCameras(camerasData.active_cameras);

                    // Try to find any active camera and set its FPS as the main indicator
                    const activeCam = camerasData.cameras.find((c: any) => c.active);
                    if (activeCam) {
                        setFps(activeCam.fps);
                    }
                }

                // Fetch Detection Stats Grouped Data
                const statsResponse = await fetch("/stats");
                if (statsResponse.ok) {
                    const statsData = await statsResponse.json();
                    setDetectionStats(statsData);
                }

            } catch (err) {
                console.error("Could not connect to Sentinel Vision backend", err);
            }
        };

        // Poll every 2 seconds
        fetchRealDetections();
        const interval = setInterval(fetchRealDetections, 2000);
        return () => clearInterval(interval);
    }, []);

    return (
        <MonitoringContext.Provider value={{
            alerts, logs, heatPoints, totalDetections, detectionStats,
            activeCameras, fps, archiveFiles, handleDetection,
            addArchiveFiles, processArchiveFile
        }}>
            {children}
        </MonitoringContext.Provider>
    );
};

export const useMonitoring = () => {
    const context = useContext(MonitoringContext);
    if (context === undefined) {
        throw new Error("useMonitoring must be used within a MonitoringProvider");
    }
    return context;
};
